### ISSUE TITLE
Multiple spelling errors

### ISSUE THREAD

**Issue by Janiru-Git** [JANIRU11/My-Porfolio-Website#1]
There are spelling mistakes in the words "colege", "developmet", "desiging"
It should be college, development and designing 
`<p class="bio">
I'm a Student of Ananda colege. I'm a member of the Ananda college ICT society
and 2 other clubs. I like web developmet, programming, desiging and gaming.
 I'm currently competing in BITS'19.
</p>`

**Comment by JANIRU11** [comment]
Ok i fixed the spelling errors
now its 
`I'm a Student of Ananda college. I'm a member of the Ananda college ICT society
and 2 other clubs. I like web development, programming, designing and gaming.
I'm currently competing in BITS'19.`
